/*
 * ADC.c
 *
 * Created: 10/6/2017 6:00:56 AM
 *  Author: Wesam
 */ 

 #include "ADC.h"

 //SET DIRECTION OF PIN#0 IN PORTA AS INPUT
 DDRA	&=~ (1U<<0);
 //SET ENABLE BIT IN THE ADC STATUS REGISTER
 ADCSRA |= (1U<<ADEN);
 //SET PRESCALER VALUE TO 8
 ADCSRA &=~(1U<<ADPS2);
 ADCSRA |= (1U<<ADPS1)|(1U<<ADPS0);
 //SET REFERENCE VOLTAGE TO BE INTERNAL = 2.56
 ADMUX  |= (1U<<REFS0)|(1U<REFS1);
 //SELECT INPUT CHANNEL TO BE CHANNEL 0 -> PIN#0 IN PORTA
 ADMUX  |= (1U<<MUX0);
 //START CONVERSION
 ADCSRA |= (1U<<ADSC);
 //ENABLE GLOBAL INTERRUPT
 sei();
 //ENABLE ADC INTERRUPT
 ADCSRA |= (1U<<ADIE);
 //WAIT FOR CONVERSION
 while ( (ADCSRA & 1U<<ADIF) == 0 );
  
